name: CI

on:
  push:
    branches:
      - master
      - ci
  pull_request:

jobs:
  format:
    name: Code linting
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir environment
        uses: erlef/setup-elixir@v1
        with:
          otp-version: "22.2"
          elixir-version: "1.9"

      - run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check compilation warnings
        run: mix compile --warnings-as-errors

  test:
    name: Test suite
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        versions:
          - otp: "19.3"
            elixir: "1.6"
          - otp: "22.2"
            elixir: "1.9"

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir environment
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          otp-version: ${{ matrix.versions.otp }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test
